[package]
name = "fanta"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
fern = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
