[package]
name = "source_analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
topological-sort = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
threadbound = { workspace = true }
