[package]
name = "walking_engine"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
coordinate_systems = { workspace = true }
itertools = { workspace = true }
kinematics = { workspace = true }
linear_algebra = { workspace = true }
motionfile = { workspace = true }
nalgebra = { workspace = true }
path_serde = { workspace = true }
serde = { workspace = true }
splines = { workspace = true }
types = { workspace = true }
num-traits = { workspace = true }
