[package]
name = "serialize_hierarchy"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
bincode = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serialize_hierarchy_derive = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
