[package]
name = "hulkz-stream"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
enumset = "1.1.10"
hulkz = { workspace = true }
mcap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.43.0", default-features = false, features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-util = { version = "0.7.13", default-features = false, features = ["rt"] }
tracing = { workspace = true }
zenoh = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
