[package]
name = "mujoco-rust-server"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
name = "mujoco_rust_server"
crate-type = ["cdylib"]

[dependencies]
bincode = { workspace = true }
booster = { workspace = true, features = ["pyo3"] }
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }
futures-util = { workspace = true }
linear_algebra = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true }
pyo3-async-runtimes = { workspace = true }
pyo3-log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
simulation_message = { workspace = true, features = ["pyo3"] }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }
zed = { workspace = true, features = ["pyo3"] }
