[project]
name = "mujoco-rust-server"
version = "0.1.0"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "mujoco_rust_server/**" },
    { file = "src/**" },
    { file = "Cargo.toml" },
    { file = "Cargo.lock" },
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = []
