[package]
name = "zed"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
pyo3 = { workspace = true, optional = true }
ros2 = { workspace = true }
serde = { workspace = true }

[features]
pyo3 = ["dep:pyo3"]
