[package]
name = "simulation_message"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
booster = { workspace = true }
pyo3 = { workspace = true, optional = true }
ros2 = { workspace = true }
serde = { workspace = true }

[features]
pyo3 = ["dep:pyo3", "booster/pyo3"]
