version: "3"
services:
  runner-01:
    container_name: hulks-github-runner-v2-01
    image: hulks-github-runner-v2
    build:
      context: .
      args:
        - RUNNER_VERSION=2.299.1
        - SDK_VERSION=5.1
    restart: always
    volumes:
      - hulks-github-runner-v2-01:/ci/actions-runner
    environment:
      - CARGO_HOME=/ci/actions-runner/cargo
      - CARGO_TARGET_DIR=/ci/actions-runner/target
  runner-02:
    container_name: hulks-github-runner-v2-02
    image: hulks-github-runner-v2
    build:
      context: .
      args:
        - RUNNER_VERSION=2.299.1
        - SDK_VERSION=5.1
    restart: always
    volumes:
      - hulks-github-runner-v2-02:/ci/actions-runner
    environment:
      - CARGO_HOME=/ci/actions-runner/cargo
      - CARGO_TARGET_DIR=/ci/actions-runner/target
  runner-03:
    container_name: hulks-github-runner-v2-03
    image: hulks-github-runner-v2
    build:
      context: .
      args:
        - RUNNER_VERSION=2.299.1
        - SDK_VERSION=5.1
    restart: always
    volumes:
      - hulks-github-runner-v2-03:/ci/actions-runner
    environment:
      - CARGO_HOME=/ci/actions-runner/cargo
      - CARGO_TARGET_DIR=/ci/actions-runner/target
  runner-04:
    container_name: hulks-github-runner-v2-04
    image: hulks-github-runner-v2
    build:
      context: .
      args:
        - RUNNER_VERSION=2.299.1
        - SDK_VERSION=5.1
    restart: always
    volumes:
      - hulks-github-runner-v2-04:/ci/actions-runner
    environment:
      - CARGO_HOME=/ci/actions-runner/cargo
      - CARGO_TARGET_DIR=/ci/actions-runner/target
  runner-05:
    container_name: hulks-github-runner-v2-05
    image: hulks-github-runner-v2
    build:
      context: .
      args:
        - RUNNER_VERSION=2.299.1
        - SDK_VERSION=5.1
    restart: always
    volumes:
      - hulks-github-runner-v2-05:/ci/actions-runner
    environment:
      - CARGO_HOME=/ci/actions-runner/cargo
      - CARGO_TARGET_DIR=/ci/actions-runner/target
volumes:
  hulks-github-runner-v2-01:
  hulks-github-runner-v2-02:
  hulks-github-runner-v2-03:
  hulks-github-runner-v2-04:
  hulks-github-runner-v2-05:
