[package]
name = "ros2"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
serde = { workspace = true }
nalgebra = { workspace = true }