[package]
name = "ros2"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
image = { workspace = true }
nalgebra = { workspace = true }
path_serde = { workspace = true }
pyo3 = { workspace = true, optional = true }
serde = { workspace = true }

[features]
pyo3 = ["dep:pyo3"]
