[package]
name = "ros2"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
nalgebra = { workspace = true }
path_serde = { workspace = true }
serde = { workspace = true }
