[package]
edition = "2021"
license = "GPL-3.0-only"
name = "repository"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spl_network = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
