[package]
name = "repository"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
futures-util = { workspace = true }
home = { workspace = true }
hula_types = { workspace = true }
itertools = { workspace = true }
parameters = { workspace = true }
pathdiff = { workspace = true }
robot = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spl_network_messages = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
xdg = { workspace = true }
