[package]
name = "hardware"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
booster.workspace = true
color-eyre = { workspace = true }
hula_types = { workspace = true }
ros2 = { workspace = true }
types = { workspace = true }
zed = { workspace = true }