[package]
name = "depp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
color-eyre = { workspace = true }
toml = { workspace = true }
