[package]
name = "hulk"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
audio = { workspace = true }
bincode = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true, features = ["server"] }
control = { workspace = true }
framework = { workspace = true }
geometry = { workspace = true }
hardware = { workspace = true }
ittapi = {  workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serialize_hierarchy = { workspace = true }
spl_network = { workspace = true }
spl_network_messages = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
vision = { workspace = true }

[build-dependencies]
code_generation = { workspace = true }
color-eyre = { workspace = true }
source_analyzer = { workspace = true }
