[package]
name = "hulk"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[features]
nao = ["alsa", "nao_camera", "v4l"]

[dependencies]
alsa = { optional = true, workspace = true }
color-eyre = { workspace = true }
constants = { workspace = true }
chrono = { workspace = true }
ctrlc = { workspace = true }
cyclers = { workspace = true }
fern = { workspace = true }
i2cdev = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
nao_camera = { optional = true, workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
structs = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
v4l = { optional = true, workspace = true }
webots = { optional = true, workspace = true }
