[package]
name = "hulk_webots"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ball_filter = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
ctrlc = { workspace = true }
fern = { workspace = true }
framework = { workspace = true }
hardware = { workspace = true }
hulk = { workspace = true }
linear_algebra = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spl_network = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
webots = { workspace = true }
