[package]
name = "twix"
version = "0.8.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
aliveness = { workspace = true }
argument_parsers = { workspace = true }
ball_filter = { workspace = true }
bincode = { workspace = true }
buffered_watch = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
convert_case = { workspace = true }
coordinate_systems = { workspace = true }
dirs = { workspace = true }
eframe = { workspace = true }
egui_dock = { workspace = true }
egui_extras = { workspace = true }
egui_plot = { workspace = true }
fern = { workspace = true }
framework = { workspace = true }
fuzzy-matcher = { workspace = true }
geometry = { workspace = true }
gilrs = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
kinematics = { workspace = true }
linear_algebra = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
parameters = { workspace = true }
projection = { workspace = true }
repository = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spl_network_messages = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
types = { workspace = true }
walking_engine = { workspace = true }
