[package]
name = "twix"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
bincode = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
convert_case = { workspace = true }
eframe = { workspace = true }
egui_dock = { workspace = true }
egui_extras = { workspace = true }
fern = { workspace = true }
fuzzy-matcher = { workspace = true }
geometry = { workspace = true }
gilrs = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
parameters = { workspace = true }
projection = { workspace = true }
repository = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
