[package]
name = "twix"
version = "0.12.3"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
aliveness = { workspace = true }
argument_parsers = { workspace = true }
ball_filter = { workspace = true }
bevy = { workspace = true, features = [
  "bevy_render",
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_gizmos",
  "bevy_window",
  "bevy_pbr",
  "tonemapping_luts",
] }
bevy_mujoco = { workspace = true }
bincode = { workspace = true }
buffered_watch = { workspace = true }
calibration = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
convert_case = { workspace = true }
coordinate_systems = { workspace = true }
dirs = { workspace = true }
eframe = { workspace = true }
egui_bevy = { workspace = true }
egui_dock = { workspace = true }
egui_extras = { workspace = true }
egui_plot = { workspace = true }
framework = { workspace = true }
futures-util = { workspace = true }
geometry = { workspace = true }
gilrs = { workspace = true }
hula_types = { workspace = true }
hulk_widgets = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
kinematics = { workspace = true }
levenberg-marquardt = { workspace = true }
linear_algebra = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
parameters = { workspace = true }
projection = { workspace = true }
repository = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
step_planning = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
types = { workspace = true }
