[package]
name = "twix"
version = "0.3.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
aliveness = { workspace = true }
bincode = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
convert_case = { workspace = true }
eframe = { workspace = true }
egui_dock = { workspace = true }
egui_extras = { workspace = true }
egui_plot = { workspace = true }
fern = { workspace = true }
fuzzy-matcher = { workspace = true }
geometry = { workspace = true }
gilrs = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
parameters = { workspace = true }
projection = { workspace = true }
repository = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
