[package]
name = "hulk_booster"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[package.metadata.pepsi]
cross-compile = true

[dependencies]

approx = { workspace = true }
ball_filter = { workspace = true }
bincode = { workspace = true }
booster = { workspace = true }
buffered_watch = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
cdr = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true }
coordinate_systems = { workspace = true }
ctrlc = { workspace = true }
derive_more = { workspace = true }
env_logger = { workspace = true }
fern = { workspace = true }
framework = { workspace = true }
futures-util = { workspace = true }
geometry = { workspace = true }
hardware = { workspace = true }
hsl_network = { workspace = true }
hsl_network_messages = { workspace = true }
hula_types = { workspace = true }
hulk_widgets = { workspace = true }
ittapi = { workspace = true }
libc = { workspace = true, optional = true }
linear_algebra = { workspace = true }
log = { workspace = true }
motion = { workspace = true }
object_detection = { workspace = true }
parameters = { workspace = true }
parking_lot = { workspace = true }
path_serde = { workspace = true }
projection = { workspace = true }
ros2 = { workspace = true }
sensor_receiver = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
systemd = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
walking_inference = { workspace = true }
world_state = { workspace = true }
zenoh = { workspace = true }

[build-dependencies]
code_generation = { workspace = true }
color-eyre = { workspace = true }
hulk_manifest = { workspace = true }
source_analyzer = { workspace = true }

[features]
realtime = ["libc"]
systemd = ["dep:systemd"]
is_webots = []
