[package]
name = "hulk_imagine"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
audio = { workspace = true }
ball_filter = { workspace = true }
bincode = { workspace = true }
booster = { workspace = true }
buffered_watch = { workspace = true }
calibration = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
control = { workspace = true }
coordinate_systems = { workspace = true }
energy_optimization = { workspace = true }
framework = { workspace = true }
geometry = { workspace = true }
hardware = { workspace = true }
hsl_network = { workspace = true }
hsl_network_messages = { workspace = true }
hula_types = { workspace = true }
indicatif = { workspace = true }
ittapi = { workspace = true }
linear_algebra = { workspace = true }
mcap = { workspace = true }
motionfile = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
parameters = { workspace = true }
path_serde = { workspace = true }
projection = { workspace = true }
rmp-serde = { workspace = true }
ros2 = { workspace = true }
sensor_receiver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
step_planning = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
walking_inference = { workspace = true }
world_state = { workspace = true }
zed = { workspace = true }

[build-dependencies]
code_generation = { workspace = true }
color-eyre = { workspace = true }
hulk_manifest = { workspace = true }
source_analyzer = { workspace = true }

[features]
with_detection = []
