[package]
name = "spl_network"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
bincode = { workspace = true }
color-eyre = { workspace = true }
context_attribute = { workspace = true }
framework = { workspace = true }
hardware = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
