[package]
edition = "2021"
name = "spl_network"
version = "0.1.0"
license = "GPL-3.0-only"

[build-dependencies]
bindgen = { workspace = true }

[dependencies]
anyhow = { workspace = true }
approx = { workspace = true }
byteorder = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
