[package]
name = "simulation-message"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ros2 = { workspace = true }
booster = { workspace = true }
serde = { workspace = true }
zed = { workspace = true }