[package]
name = "spl_network_messages"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[build-dependencies]
bindgen = { workspace = true }

[dependencies]
approx = { workspace = true }
color-eyre = { workspace = true }
nalgebra = { workspace = true }
num-derive = {workspace = true}
num-traits = {workspace = true}
serde = { workspace = true }
serialize_hierarchy = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
