[package]
edition = "2021"
license = "GPL-3.0-only"
name = "behavior_simulator"
version = "0.1.0"

[[bin]]
name = "behavior_simulator"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
communication = { workspace = true, features = ["server"] }
control = { workspace = true }
ctrlc = { workspace = true }
fern = { workspace = true }
framework = { workspace = true }
hardware = { workspace = true }
ittapi = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
parameters = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serialize_hierarchy = { workspace = true }
spl_network_messages = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
context_attribute = { workspace = true }

[build-dependencies]
code_generation = { workspace = true }
color-eyre = { workspace = true }
source_analyzer = { workspace = true }
