[package]
name = "projection"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
nalgebra = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
