[package]
name = "projection"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dev-dependencies]
approx = { workspace = true }

[dependencies]
approx = { workspace = true }
coordinate_systems = { workspace = true }
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
path_serde = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true }
