[package]
name = "vision"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
approx = { workspace = true }
calibration = { workspace = true }
color-eyre = { workspace = true }
context_attribute = { workspace = true }
coordinate_systems = { workspace = true }
fast_image_resize = { workspace = true }
filtering = { workspace = true }
framework = { workspace = true }
geometry = { workspace = true }
hardware = { workspace = true }
itertools = { workspace = true }
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
projection = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
ransac = { workspace = true }
ros2 = { workspace = true }
serde = { workspace = true }
types = { workspace = true }
