[package]
name = "vision"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
approx = { workspace = true }
color-eyre = { workspace = true }
compiled-nn = { workspace = true }
context_attribute = { workspace = true }
fast_image_resize = { workspace = true }
filtering = { workspace = true }
framework = { workspace = true }
geometry = { workspace = true }
hardware = { workspace = true }
itertools = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
projection = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
types = { workspace = true }
