[package]
name = "pepsi"
version = "5.2.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
aliveness = { workspace = true }
argument_parsers = { workspace = true }
bat = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
color-eyre = { workspace = true }
futures-util = { workspace = true }
glob = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
nao = { workspace = true }
opn = { workspace = true }
pathdiff = { workspace = true }
regex = { workspace = true }
repository = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
source_analyzer = { workspace = true }
spl_network_messages = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
