[package]
edition = "2021"
license = "GPL-3.0-only"
name = "pepsi"
version = "2.4.1"

[dependencies]
anyhow = { workspace = true }
bat = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
futures = { workspace = true }
nao = { workspace = true }
regex = { workspace = true }
repository = { workspace = true }
spl_network = { workspace = true }
tokio = { workspace = true }
