[package]
name = "pepsi"
version = "2.7.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
aliveness = { workspace = true }
bat = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
color-eyre = { workspace = true }
constants = { workspace = true }
futures-util = { workspace = true }
indicatif = { workspace = true }
nao = { workspace = true }
regex = { workspace = true }
repository = { workspace = true }
serde_json = { workspace = true }
source_analyzer = { workspace = true }
spl_network_messages = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
