[package]
name = "types"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = { workspace = true }
approx = { workspace = true }
image = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serialize_hierarchy = { workspace = true }
spl_network = { workspace = true }
