[package]
name = "hulk_nao"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
alsa = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
constants = { workspace = true }
ctrlc = { workspace = true }
enum-iterator = { workspace = true }
fern = { workspace = true }
hardware = { workspace = true }
hulk = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
nao_camera = { workspace = true }
opusfile-ng = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spl_network = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
