[project]
name = "konerl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "mjlab>=0.1.0",
    "mujoco>=3.4.0",
    "numpy>=2.4.0",
    "onnxruntime>=1.24.1",
    "pyopengl-accelerate>=3.1.10",
    "scipy>=1.16.3",
]

[tool.uv.sources]
konerl = { workspace = true }
mjlab = { git = "https://github.com/mujocolab/mjlab.git" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
stubPath = "stubs/"

[tool.ruff]
exclude = ["typings/", "stubs/"]
line-length = 120

[project.entry-points."mjlab.tasks"]
k1_velocity = "konerl.tasks.k1_velocity_tracking"
