[package]
name = "control"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
approx = { workspace = true }
color-eyre = { workspace = true }
context_attribute = { workspace = true }
itertools = { workspace = true }
filtering = { workspace = true }
framework = { workspace = true }
kinematics = { workspace = true }
log = { workspace = true }
motionfile = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
projection = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serialize_hierarchy = { workspace = true }
smallvec = { workspace = true }
spl_network_messages = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true }
